version: '3'
services:
  jupyter-tutorial:
    build: .
    container_name: jupyter.local
    ports:
      - "8888:8888"
      - "80:5000"
    volumes:
      - ./work:/home/jovyan/work/
    command: start-notebook.sh --NotebookApp.token=''
  mysql:
    image: mysql:5.7
    container_name: cc104.mysql.local
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/data/db/
    environment:
      - MYSQL_ROOT_PASSWORD=iii
